"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  set syntax=on
  set background=dark
  filetype off
  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()

  Bundle 'altercation/vim-colors-solarized'

  filetype plugin indent on  " required!"
  let g:airline_powerline_fonts = 1
  let g:vundles=['general', 'git', 'hg', 'programming', 'completion', 'java', 'cpp', 'ruby', 'python', 'misc']
  "let g:vundles=['general', 'programming']
  let g:neocomplcache_enable_at_startup = 1
  " Load 'vundles'
  source ~/.vim/vundles.vim
  " Add extra bundles here...
  " Bundle 'reponame'
endif

" Customize to your needs...
set mouse=
syntax enable
set background=dark
colorscheme solarized
